### ISSUE TITLE
Putting the Open Data Into Open Budgets

### ISSUE THREAD

**Issue by jwyg** [openspending/community.openspending.org#24]
http://openspending.org/resources/osi/appendix-open-budgets-open-data.html

Here's where I'd mention all of the confusion around 'open' and 'standard' language. And perhaps if we need to mention it in text above, we can just link here?

"We have looked in detail in this report at criteria which make it difficult for organisations to use data that has been released by governments." -> "In this report we have looked at obstacles to civil society organisations using data on public finance to support their mission."

Again I'd harmonise titles/nesting, which is currently somewhat confusing. Or hold the hand of the reader a bit more and guide them through narrative of the text.

**Comment by danfowler** [comment]
Closing as I assume the text of the report has been finalized (at least for now).
