### ISSUE TITLE
Migrate Community.OpenSpending.org back to github pages / jekyll-based site

### ISSUE THREAD

**Issue by rufuspollock** [openspending/community.openspending.org#28]
**Update: the in progress analysis and plan is in this [google doc](https://docs.google.com/document/d/1WmkI7RBd9GVXyROgZamZZKMBKfbOAEO0jxF-jfk1f1k/edit)**
- [x] Review this repo
- [x] Identify diff with current wordpress powered community.openspending.org
- [x] Detail content migration
- [x] Re-theme
- [x] Detail other migration (e.g. DNS etc)
### Detailed Items

Note: _italics_ indicate less important items we could leave until later.
#### Blog migration
- [x] migrate blog - see #34 
#### Resources Section

The /resources/ links currently point to the old content as it already exists in the repo so they (with the exception of the EU report) are not yet formatted in accordance with the theme.

Sort resources section (i.e. get theme working for all sections, remove /refactor any irrelevant stuff e.g. the index page for resources section probably needs work)

Resources is currently a catch-all folder and I'm inclined to distinguish among different types of resources via YAML metadata (e.g. 'report: true', 'archived: true').
- [x] `resources/*` - remove bespoke layouts and use default
  - check if any layouts do more than set breadcrumbs
  - think about markdownify-ing html
- [x] `resources/gift` - can just use default layout for now and worry about bespoke layout later
- [x] resources/gb-spending
  - ignore `/report/` - just leave as is
#### Misc Other
- [x] Should information about contributing go under both /help/ and /get-involved/?
  - Ans: No. I think contributing is probably under get-involved. All in all i think we could simplify a bit here.
- [ ] _Front page - still needs some work (e.g. to link to core sections)_
  - Also should we auto-expand menu (may not be obvious to users)
  - Tweak tagline - cf current community site ...
  - Point to main database - people may have ended up here and wonder where the data is!
- [x] Edit this page / Contribute to this page on _every_ page
  - We can leave off front page if not obvious where this would go
- [ ] _Page history (like Edit this Page) - linking to git history on github_
- [ ] _Work out all redirects and implement them in _config.yml_
- [x] Put in place contribution guidelines (can borrow from e.g. opendatahandbook) - i.e. how do i edit this page
  - Shall we put these under a dedicated `/meta/` section of the site i.e. at `/meta/contribute/` or similar (there is other meta stuff we can have e.g. recent changes - see #33)
- [x] Remove author display (do this in _layouts for present)
### Actual Switchover
- [x] commit CNAME file to repo: community.openspending.org
- [x] shorten TTL before changing DNS records
- [x] update CNAME in DNS records of community.openspending.org to [point to GitHub](https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/)
- [x] undo redirection of blog.openspending.org to community.openspending.org
- [x] redirect community.openspending.org/blog to blog.openspending.org (to catch old links)
- [x] reset TTL after changing DNS records
- [x] Google Analytics
### Refactor old site
- [x] Move current WP community.openspending.org to openspending.okblogfarm.org

**Comment by rufuspollock** [comment]
Please add your name here if you are interested in contributing (no technical expertise is needed).

**Comment by danfowler** [comment]
- [ ] ~~commit CNAME file to repo: community.openspending.org~~
- [ ] ~~shorten TTL before changing DNS records~~
- [ ] ~~update CNAME in DNS records of community.openspending.org to [point to GitHub](https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/)~~
- [ ] ~~undo redirection of blog.openspending.org to community.openspending.org~~
- [ ] ~~redirect community.openspending.org/blog to blog.openspending.org (to catch old links)~~
- [ ] ~~reset TTL after changing DNS records~~

**Comment by rufuspollock** [comment]
@danfowler great points and i've merged back up to main issue and added some other stuff.

**Comment by rufuspollock** [comment]
@danfowler i've just added a point about a `/meta/` section for contribute stuff - see description.

**Comment by danfowler** [comment]
Now that the bulk of the main migration tasks are completed, will make new issue for remaining cleanup tasks.
