### ISSUE TITLE
Migrating blog to Jekyll?

### ISSUE THREAD

**Issue by pwalsh** [openspending/community.openspending.org#34]
Are there plans to migrate the blog to Jekyll along with the community site?

**Comment by danfowler** [comment]
The plan is to leave the blog on Wordpress for the moment.

**Comment by rufuspollock** [comment]
@pwalsh basic answer is: "yes" - but right now we may leave on wordpress to save time. real question is the benefit of all in one vs any barriers (we get more users blogging) and/orr lack of features for jekyll as blogging platform.

@danfowler if you think it would be easy to migrate the blog maybe we should just go for it (it may actually save time to have everything in one place and not have to fix redirects as much). wdyt?

**Comment by rufuspollock** [comment]
@danfowler wdyt on taking this on? I think we go do this and just shut wordpress down.

**Comment by danfowler** [comment]
Yes, this is very doable.  I have the posts already from wordpress export, so they can be easily added to dotorg repo.

**Comment by rufuspollock** [comment]
Let's do it.

One question: I guess for the blog we won't go for our `/.../.../` naming but will allow .html on page names (or do we want to keep that model and just posts in an index.md inside a directory ...).

**Comment by danfowler** [comment]
`permalink: /:categories/:year/:month/:title/`will allow each post's link to have a trailing slash without needing an index.md in a directory.

**Comment by rufuspollock** [comment]
sounds great!

**Comment by danfowler** [comment]
Blog is migrated.
