### ISSUE TITLE
Remove non-existent layouts

### ISSUE THREAD

**Issue by danfowler** [openspending/community.openspending.org#36]

**Comment by smth** [comment]
Was this in relation to the `Layout 'x' requested in y does not exist.` warnings? I'm just running this for the first time and seeing lots of these.

**Comment by danfowler** [comment]
Yes, these are remnants of old pages from the previous site.  I still need to go through and think about how to represent the 'handbook' and 'standard' with the new theme.  Some of these warnings I can eliminate pretty easily by removing pages that have already been replaced with their new equivalents.

**Comment by danfowler** [comment]
I work on removing these warnings once you've made your commits.
