### ISSUE TITLE
Remaining cleanup after migration

### ISSUE THREAD

**Issue by danfowler** [openspending/community.openspending.org#39]
- [x]  Page history (like Edit this Page) - linking to git history on github
- [x] Work out all redirects and implement them in _config.yml
- [x] Front page - still needs some work (e.g. to link to core sections)
- [x] Also should we auto-expand menu (may not be obvious to users)
- [x] Tweak tagline - cf current community site ...
- [x] Point to main database - people may have ended up here and wonder where the data is!
- [x] sorting the main menu to have a sensible ordering
- [x] content tweaks (e.g. i think we thought the help section could do with some refactoring)
- [x] ensure RSS feeds work 
- [x] generate sitemap https://github.com/jekyll/jekyll-sitemap

**Comment by rufuspollock** [comment]
@danfowler i'd also add:
- sorting the main menu to have a sensible ordering
- content tweaks (e.g. i think we thought the help section could do with some refactoring)

**Comment by danfowler** [comment]
Added.

**Comment by rufuspollock** [comment]
Menu
- Home
- Get Involved
  - OpenSpending Next
  - Events
- Help and Guides
- Resources
  - EU stuff - great submenu

---
- Meta
- About
- Blog

**Comment by rufuspollock** [comment]
All we will do remaining is sort out redirects.

**Comment by danfowler** [comment]
@rgrp Was working on this just now, and noticed that the old blog post permalink format was something like:

http://community.openspending.org/2014/03/hackathon-odd14-barcelona/

(As seen here: https://twitter.com/openspending/status/449576966329339904)

Whereas the default new one would be:

http://community.openspending.org/blog/2014/03/28/hackathon-odd14-barcelona/

Should we keep the old format?  The main (weird) thing would be losing the /blog/ prefix for post permalinks.

**Comment by danfowler** [comment]
Hm, in trying to switch to a permalink style other than 'pretty' for blog posts, I ran into this issue: https://github.com/jekyll/jekyll/issues/2691

Basically, we would lose the 'pretty' permalink for pages (trailing slash) with no clear way to re-enable aside from manually renaming the files, pushing into directories, etc.

**Comment by rufuspollock** [comment]
I'm happy with subdomain blog - we will just have to do more redirect work. Happy for you to call it.

**Comment by danfowler** [comment]
Cool. Will add redirects for old posts.

**Comment by danfowler** [comment]
Posts redirected.
