### ISSUE TITLE
Reconcile help/API navigation and page titles

### ISSUE THREAD

**Issue by psychemedia** [openspending/community.openspending.org#4]
On API help pages (eg http://openspending.org/help/api.html ) the headings in the menu down the left hand side are often completely different to the titles of the page those pages load. For example:

Financial data types -> Financial data types in OpenSpending
How we store data -> How does OpenSpending store data?

Overview -> Loading Data into OpenSpending
Cleaning Data -> How Do I Clean My Data?
Extending Data -> How can I extend my data?

Overview -> Guide for developers and designers
Aggregation-> Aggregation API
Resources -> REST resources
Full-text search -> Search API
Personal Tax -> Tax share API
Dataset loading ->  Data loading API

Do you want to help? -> Hacking on OpenSpending
Development process -> Foundations of the Development Process
Code review guidelines -> Lend us your eyeballs!

Some of the page titles have a general similarity to navigation menu link text, but some are way off, which creates confusion when trying to navigate the site.

It would be really useful to reconcile these some way - does anyone have any preferences or shall I just make changes as I see fit?

For consistency of experience, it probably makes sense to keep the navigation text and tweak the page titles?

**Comment by nmashton** [comment]
Note that we're in the process of migrating most of the dotorg site content to [blog.openspending.org](http://blog.openspending.org), which will become community.openspending.org in the near future.

I've already moved over [part of the help content](http://blog.openspending.org/help/) (with reconciled titles!), and some of it has been rewritten as part of [The OpenSpending Guide](http://blog.openspending.org/help/guide).

**Comment by danfowler** [comment]
New site reflects the organization of the Wordpress site.
