### ISSUE TITLE
Footer issues with list of funders when sidebar shown

### ISSUE THREAD

**Issue by rufuspollock** [openspending/community.openspending.org#41]
When sidebar is active on normal pages the list of funders wraps to two lines and looks bad.

I suggest we have list of funders on own separate line (e.g. second line after logo stuff).

Aside: we should add Hewlett Foundation logo.

**Comment by rufuspollock** [comment]
@mintcanary one for you (?)

**Comment by smth** [comment]
Yes, I will have a look.
