### ISSUE TITLE
Map of spending projects does not work

### ISSUE THREAD

**Issue by milafrerichs** [openspending/community.openspending.org#42]
Hello,

while going through the site I wanted to open the map of spending projects.
But it is not there:
http://community.openspending.org/resources/map-of-spending-projects/

```
*Made by Anna Flagg using D3.js.*

[iframe src="http://www.annaflagg.com/os" frameborder="0" width="620" height="320"]
```

https://github.com/openspending/dotorg/blob/gh-pages/resources/map-of-spending-projects/index.md

The iframe is not displayed and the map at
http://www.annaflagg.com/os
does not work either.

Just letting you know :)

**Comment by danfowler** [comment]
Thanks for flagging this!  As the source is no longer working, I suppose we will just remove.

**Comment by rufuspollock** [comment]
See https://trello.com/c/dvXbOghc/25-create-a-map-or-visualisation-of-our-coverage-and-use-cases - we have the underlying spreadsheet there (though i think anna flag forked it when making her map and her spreadsheet has disappeared).
