### ISSUE TITLE
Menus do not reflect context of current page

### ISSUE THREAD

**Issue by rufuspollock** [openspending/community.openspending.org#43]
Side menu is not "open" to the current page. This means that when you navigate around e.g. EU guide you lose "context".

@mintcanary any thoughts here? Does the issue make sense?

**Comment by smth** [comment]
It does make sense. This will be due to the "active" menu item not having the `Selected` class applied.

Solution is to check url and apply the class as appropriate. Something like:

```
<li {% if page.url == 'page1' %}class="Selected"{% endif %}>
  <a href="{{ site.baseurl }}/page1/">Page One</a>
</li>
```

(Will most likely need to be slightly more complicated than that)

**Comment by danfowler** [comment]
Thanks @mintcanary for the explanation.  I've resolved this issue.
