### ISSUE TITLE
Keep old URLs alive

### ISSUE THREAD

**Issue by jindrichmynarz** [openspending/community.openspending.org#45]
With the recent [restructuring of the OpenSpending.org site](http://community.openspending.org/blog/2015/07/09/openspending-community-new-home/) several URLs from the previous site structure ceased to work. For example, the page for the (now deprecated) [data standard for transaction-level spending data](http://community.openspending.org/research/standard/) no longer resolves and instead returns HTTP 404 Not found. Fortunately, the Internet Archive has some of the pages with broken URLs cached (e.g., [A data standard for transaction-level spending data](https://web.archive.org/web/20140729161633/http://community.openspending.org/research/standard/)), but it would be better if the URLs continued to resolve to allow referencing them in the future.

**Comment by danfowler** [comment]
Hey @jindrichmynarz thanks for flagging this!  That part of the site was in a git submodule that has now been updated with redirection from the old /research/standard/ URL to the new /resources/standard/ URL.  The relevant links in the navigation bar have been added, too.

**Comment by jindrichmynarz** [comment]
Great. Thanks for fixing it!

**Comment by rufuspollock** [comment]
@danfowler we should really mark the stuff in http://community.openspending.org/resources/standard/ as deprecated prominently and point people at http://fiscal.dataprotocols.org/.

Do you think we could do that? @jindrichmynarz would you like to help out - you'd be very welcome!

**Comment by danfowler** [comment]
@rgrp I added a warning to the _layout html for that section
