### ISSUE TITLE
Remove mailing list links on contact page

### ISSUE THREAD

**Issue by rufuspollock** [openspending/community.openspending.org#48]
e.g. we have links on http://community.openspending.org/about/contact/

I suggest we now remove these mailing list links in favour of the forum. Note I'm not sure the forum link is super clear so I would repeat in the bullet point lists (i.e. basically replace mailing list item in the lists with a link to the forum).

I'd also suggest we repeat the irc link under developer section (or get rid of the developer section frankly ...)

**Comment by danfowler** [comment]
I rewrote the contact page a bit and removed another reference to the mailing lists somewhere else.
