### ISSUE TITLE
Example API queries

### ISSUE THREAD

**Issue by psychemedia** [openspending/community.openspending.org#5]
I'm really struggling to make even the simplest API calls based on the documentation shown.

Has anyone got a list of example URLs for calling the API (both search API and aggregation API) for a range of "useful" queries (it would be handy to have a line or two about what the dataset represents as well as the URL)? These are a great way of helping the 'try something that already works then hack it" approach to figuring out APIs;-)

**Comment by danfowler** [comment]
Closing as it has been a long time, and this is probably a question for the forums anyway: http://discuss.okfn.org/c/openspending
