### ISSUE TITLE
Main page title and h1 in page content are same size

### ISSUE THREAD

**Issue by rufuspollock** [openspending/community.openspending.org#50]
@mintcanary just flagging it appears a page "title" and the h1 in the main content are the same size. I'd expect page title to be larger (and expect to be able to use h1s inside page content).

What do you reckon?

**Comment by smth** [comment]
Yes, the "title" is simply an `h1`. While it would be quite simple to differentiate these, I don't see the logic. If your heading is intended to denote a sub-section of the main title / part of the same article (as the desire for it to be smaller suggests), should you not be using an `h2`?

**Comment by rufuspollock** [comment]
@mintcanary the logic is that semantically a page title (i'm not talking about the first h1 in the content but about the _page title_) is different from an h1 in the page - its the overall title.

As an example see:

http://community.openspending.org/about/

Generally you could use h2 but then its odd - esp for non-tech users using markdown since `#` is just the natural thing for headings in the main page (why would you do `##`).

So request is can: page title be made "special" (or the other h1s made smaller). I note that the page title h1 has class `page-title`.

**Comment by smth** [comment]
OK, I'll make other `h1`s smaller.

In my opinion though, the additional `h1`s in that example should be `h2`s.

**Comment by pwalsh** [comment]
From an SEO perspective, there should only be one `h1` on any page - serving as the title.

**Comment by rufuspollock** [comment]
@pwalsh ok i guess then pages should always have h2s. I'm ok with that. So @mintcanary the approach here is that all markdown authors should use h2 as their top level markup when writing docs - and we don't need to change h1s.

I will fix h1 to h2s in the relevant pages to do that. Maybe we note it somewhere in instructions too but not a priority :-)

**Comment by smth** [comment]
Yes, SEO was part of my rationale (though this is becoming a less concrete rule in HTML5).

It'd be better if authors think of it in terms of the top level heading being generated automatically (which is the case).

**Comment by rufuspollock** [comment]
@mintcanary i guess that was my point here - most authors will just see the markdown and have the title auto-generated. They then need to understand that they should not use `#` but always start with `##` which is not obvious. Anyway i think we have a resolution for now.

**Comment by smth** [comment]
We could always stop creating the heading from the page `title`, and have authors insert it manually with a `#` (that would mean editing all the pages though).

**Comment by rufuspollock** [comment]
FIXED in https://github.com/openspending/dotorg/commit/54300949fd722dc57ff9bd06bca880bd4b418375
