### ISSUE TITLE
Slide Deck Introduction page (sort of an orphan)

### ISSUE THREAD

**Issue by rufuspollock** [openspending/community.openspending.org#51]
Note quite sure where this page came from: http://community.openspending.org/about/community-site/slide-deck-introduction/

I think this is a bit of an orphan and we want to delete and put slide deck on the front page or just delete and put slide deck on a page called "Presentations" or similar.

/cc @danfowler for your input as czar of the migration

**Comment by danfowler** [comment]
OK, I cleaned this up a bit :ru:

**Comment by rufuspollock** [comment]
Thanks though I'm still not sure a dedicated page is that useful - who would visit it?

Either we embed in front page (that's useful if we think deck is useful) or, if we do not think that is warranted, we probably want this in a page called "presentations" or similar where we collect not only this but other decks over time (what section this would come under is not clear but about seems reasonable).

**Comment by danfowler** [comment]
I'm not sure a slide deck is how I want to introduced to a website/community :smile:.  [/about/presentations/](http://community.openspending.org/about/presentations/) is a list of presentations. Perhaps it can be moved from a dedicated page to an entry in the "Presentations" collection, and still be listed in /about/presentations/

**Comment by rufuspollock** [comment]
OK. I would say a video or slidedeck (for those without videos) are standard intro practice on many websites i've been to - not perfect but better than a few words and allows people to get a sense of what we are doing - right now if i arrive I'm not sure i'd find out that quickly and people are notoriously poor at clicking.

As an initial move let's just get the standard presentations page and have this as one item (i did think the old site had a list of presentations somewhere too but i may be mistaken).
