### ISSUE TITLE
Get a "media" page and add links to main openspending logos

### ISSUE THREAD

**Issue by rufuspollock** [openspending/community.openspending.org#55]
May also need to work out what are the logos and whether we have all the ones we need (e.g. favicon, square one etc etc)

http://assets.okfn.org/p/openspending/img/

Note we have a square one on twitter i think ;-)

Aside: we have want to start storing assets in this repo (???)

**Comment by danfowler** [comment]
Will new logos be created for OpenSpending Next?

**Comment by danfowler** [comment]
Closed with https://github.com/openspending/community.openspending.org/commit/89699051a0f7853fcc2cc1535ce8b8df453007b4

**Comment by rufuspollock** [comment]
@danfowler could you also add a link to the page on the website where is located.

**Comment by danfowler** [comment]
@rgrp there's a link to the "media" page from [/meta/](http://community.openspending.org/meta/)
