### ISSUE TITLE
Removing old broken links in all pages

### ISSUE THREAD

**Issue by cecilaki** [openspending/community.openspending.org#57]
Part of a content cleaning I spotted several pages with old broken links. 
I will remove the old video links in the help section. It definitely doesn't help any more:) 
http://community.openspending.org/help/

If you spot any others (and that might be the case) report it here or replace depending on the cases

**Comment by danfowler** [comment]
@cecilaki I've made a major refactor of the site which should address some of these issues.  I've added a deprecation warning for all /help/.  

As you see more problems, please make new issues (maybe per page?)
