### ISSUE TITLE
Style a better alignment of pictures

### ISSUE THREAD

**Issue by cecilaki** [openspending/community.openspending.org#58]
In this page, would like to get the pics smaller + align them to each description

https://github.com/openspending/dotorg/blob/gh-pages/about/steering-group/index.md

**Comment by danfowler** [comment]
I'm thinking putting each person in its own div, floating the figures (photos) left, and centering the figure captions.  I'd add this to main.scss

@mintcanary is there a more general solution that maps to Open Knowledge style guidelines?  Or do you have any specific guidelines on modifying the site Sass?

**Comment by smth** [comment]
This is not really addressed in the guidelines. There is a suggestion that images should be within circles, but as this site deliberately ignores the guidelines in other respects, I wouldn't worry about that.

To lay this out I'd float the figures, as you suggest and give a left margin to the corresponding text. I think the figcaptions (names in this case) are fine left aligned, though may make more sense presented as headings for the subsequent text.

No strong guidelines as to where you add the SAAS, as I recall, it's not particularly well organised at the moment. I would suggest that as this is a new 'feature', you create a new scss file for it [here](https://github.com/openspending/dotorg/tree/gh-pages/_sass) and import it into main.scss. That'll make it a little easier to bolt onto other sites.

**Comment by danfowler** [comment]
@mintcanary great suggestions, thanks
