### ISSUE TITLE
Exposing API Calling URL Links in Data Views

### ISSUE THREAD

**Issue by psychemedia** [openspending/community.openspending.org#6]
Would it be useful to provide a link to an API query URL for views over data generated in the search interface for each dataset?

For example, if I search a particular dataset for a particular term and then select a few filters/facets, if we provided a link to the corresponding API call it would allow users to use openspending.org to build up a query/data view, and then grab a link that they could use to pull the data directly into another application.

This approach makes the API available to users who may be confident in consuming the data, or plugging an API calling URL into a library that can handle that data, but who struggles to make sense of the API documentation (or can't be bothered to read it...)

**Comment by danfowler** [comment]
Closing as it has been a long time, and this is probably a question for the forums anyway: http://discuss.okfn.org/c/openspending
