### ISSUE TITLE
Unable to add source file(s) for a dataset for Malaysia Federal Budget.

### ISSUE THREAD

**Issue by ghost** [openspending/community.openspending.org#61]
I'm facing a problem in uploading a source file for a dataset for Malaysia Federal Budget.

I have tried using the Google publish link https://docs.google.com/spreadsheets/d/1yvXOtK4W9VSWtXm3sTZmS3V1jD8tqTI5e9nkGSmwywY/pub?gid=108177500&single=true&output=csv and the Plone link (from Sinar Project website) http://sinarproject.org/en/projects/open-spending-1/bajet-2015-ministerial-level-xlsx-sheet2-csv-bajet-2015-ministerial-level-xlsx-sheet2-csv.csv/view but both links didn't work. The status is "Still Analysing" for more than 10 minutes after refreshing for several times.

I've filed an issue here but I'm not sure if its under the correct repo.

Kindly advice.

**Comment by danfowler** [comment]
Hi @Hazwany, the specific issue should be resolved.  Can you try adding your file now?

**Comment by danfowler** [comment]
Resolved.
