### ISSUE TITLE
why does sidebar open automatically after I open the page?

### ISSUE THREAD

**Issue by hoony-o-1** [openspending/community.openspending.org#65]
To me, it's something troublesome. Of course, there should be a reason to make it this way, but I'd like to hear other's thoughts :space_invader:

**Comment by rufuspollock** [comment]
This was supposed to be front page only.

**Comment by danfowler** [comment]
It is :).

**Comment by hoony-o-1** [comment]
I thought it's till tiresome to me even on front page only. :) got it!
