### ISSUE TITLE
OK Panel needs updating

### ISSUE THREAD

**Issue by smth** [openspending/community.openspending.org#73]
Should be updated to use sources specified [here](http://a.okfn.org/html/oki/panel/).

Will in turn require [a small patch](https://github.com/okfn/handbook-theme/commit/8513c2da52e65ac413886b90427662fb3907f463) to this theme.

Edit: actually, [this patch](https://github.com/okfn/handbook-theme/commit/b05eb53eee22fefac4c0b5f2ee1f2e56d5a4d1ab).

**Comment by cecilaki** [comment]
Ok. Do you take care of the patch in the community site then?  
Excellent UX by the way!

**Comment by smth** [comment]
I suggest one person does both, that person can be me. Just noting here so it doesn't get forgotten.

**Comment by cecilaki** [comment]
If you're happy with it, then it could be you and it won't be forgotten.
With both, do you refer to the community + openspending.org?

**Comment by smth** [comment]
By both I meant:
- Sources updated
- Patch applied
