### ISSUE TITLE
Subtitle

### ISSUE THREAD

**Issue by jwyg** [openspending/community.openspending.org#8]
http://openspending.org/resources/osi/

"How civil society organisations use technology to wrangle government spending data. " -> is this just about wrangling spending data? Given the threefold mission you mention in the introduction, isn't this more about how CSOs use data about public finances (and not just spending)?

Hence what about: "How civil society organisations use data about public finances"?

Also this should be updated in the image - whatever it turns out to be...

**Comment by danfowler** [comment]
Closing as I assume the text of the report has been finalized (at least for now).
