### ISSUE TITLE
Mapquest tile access broken

### ISSUE THREAD

**Issue by seegerseeger** [openspending/community.openspending.org#80]
The mapquest links across the site are not working anymore, see screenshot from http://labs.openspending.org/maps/
![screen shot 2016-07-14 at 17 17 44](https://cloud.githubusercontent.com/assets/9677965/16845216/73dc5df6-49e8-11e6-90b9-7ab9d08fabb3.png)

**Comment by tlacoyodefrijol** [comment]
Outdated. New version won't include mapquest map or links to labs.openspending.org. Closing issue
